package fr.plaglefleau.api.models.currencyapi

data class Data(
    val AUD: Double? = null,
    val BGN: Double? = null,
    val BRL: Double? = null,
    val CAD: Double? = null,
    val CHF: Double? = null,
    val CNY: Double? = null,
    val CZK: Double? = null,
    val DKK: Double? = null,
    val EUR: Double? = null,
    val GBP: Double? = null,
    val HKD: Double? = null,
    val HRK: Double? = null,
    val HUF: Double? = null,
    val IDR: Double? = null,
    val ILS: Double? = null,
    val INR: Double? = null,
    val ISK: Double? = null,
    val JPY: Double? = null,
    val KRW: Double? = null,
    val MXN: Double? = null,
    val MYR: Double? = null,
    val NOK: Double? = null,
    val NZD: Double? = null,
    val PHP: Double? = null,
    val PLN: Double? = null,
    val RON: Double? = null,
    val RUB: Double? = null,
    val SEK: Double? = null,
    val SGD: Double? = null,
    val THB: Double? = null,
    val TRY: Double? = null,
    val USD: Double? = null,
    val ZAR: Double? = null,
)